### ISSUE TITLE
关于HttpConnectTunnel.java类的一个问题

### ISSUE THREAD

**Issue by yanggis** [andforce/SmartZPN#2]
看了一下源代码，里面Http协议的连接，是通过这个方法这个函数建立连接的：
    @Override
    protected void onConnected(ByteBuffer buffer) throws Exception {
        System.out.printf("%s\n",session.RemoteHost);
        String request = String.format("CONNECT %s:%d HTTP/1.0\r\nProxy-Connection: keep-alive\r\nUser-Agent: %s\r\nX-App-Install-ID: %s\r\n\r\n", 
                m_DestAddress.getHostName(),
                m_DestAddress.getPort(),
                ProxyConfig.Instance.getUserAgent(),
                ProxyConfig.AppInstallID);
        buffer.clear();
        buffer.put(request.getBytes());
        buffer.flip();
        if(this.write(buffer,true)){//发送连接请求到代理服务器
            this.beginReceive();//开始接收代理服务器响应数据
        }
    }

但是，现在有一个问题，就是这个连接是基于HTTP/1.0版本的， 现在很多代理服务器都不支持HTTP/1.0版本了，有没有办法在这个函数里修改一下，使它变成基于HTTP/1.1版本的连接呢？求答复，谢谢。

**Comment by andforce** [comment]
直接改成HTTP/1.1应该也是可以的~你可以尝试一下，这段古老的代码源自古老的SmartProxy，一直没出什么问题，我也没深究~

**Comment by yanggis** [comment]
直接修改这一行是不行的，我已经尝试过了。
System.out.printf("%s\n",session.RemoteHost);
String request = String.format("CONNECT %s:%d HTTP/1.0\r\nProxy-Connection: keep-alive\r\nUser-Agent: %s\r\nX-App-Install-ID: %s\r\n\r\n", 
m_DestAddress.getHostName(),
m_DestAddress.getPort(),
ProxyConfig.Instance.getUserAgent(),
ProxyConfig.AppInstallID);
因为如果修改成http/1.1版本，这个连接字符串直接修改是不行的，因为修改就要加上GET或者POST，但是这个函数还没法判断到底该用GET还是POST。

**Comment by andforce** [comment]
我又大体看了一下，这样写应该是没有问题的~CONNECT只是类似打开一个管道，管道打开之后，GET和POST操作在trySendPartOfHeader（）函数中操作。

这样做可能是为了兼容1.0吧，因为我看在afterReceived中有正则匹配 matches("^HTTP/1.[01] 200$") ，如果你所说的服务器确实不兼容，我觉得你可以参考：https://www.web-tinker.com/article/20055.html 这文章中所说的：

> CONNECT www.web-tinker.com:80 HTTP/1.1
> 
> Host: www.web-tinker.com:80
> 
> Proxy-Connection: Keep-Alive
> 
> Proxy-Authorization: Basic *
> 
> Content-Length: 0
> 
> 　　所有的HTTP头都是类似的，第一行是方法名、主要参数、HTTP版本。接着一行一个参数，最后用两个换行来结束。这个HTTP头其实也没什么好介绍的，唯一一个重点的地方就是星号的部分，这个地方应该填写验证的用户名和密码。而且，用户名和密码也是有固定格式的。要把用户名和密码用冒号连接起来，再经过BASE64的编码后才可以使用。假如用户名是abc密码是123，那么星号的地方就应该换上YWJjOjEyMw==，也就是abc:123经过BASE64编码的结果。
> 　　发送完这个请求之后，就是服务器端响应请求了。如果用户名和密码验证通过，就会返回一个状态码为200的响应信息。虽然状态码是200，但是这个状态描述不是OK，而是Connection Established。

**Comment by yanggis** [comment]
您好，感谢回复，我现在知道问题在哪里了，问题的关键就在这个connect方法上，因为现在很多的代理服务器都不允许在非ssl端口上使用connect方法连接服务器，会返回403错误。所以我刚才试了HTTP/1.1和HTTP/1.0都会返回403被禁止访问。但是采用普通的Get或者POST方法是可以正常访问的。

所以这个地方如果要把connect方法改成post和get和代理服务器通讯，容易修改吗？

**Comment by andforce** [comment]
这个可能需要你自己尝试一下了，最近没多余的精力折腾这个了~希望弄清楚之后告诉我哈~

**Comment by yanggis** [comment]
OK，谢谢。
